// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB9B6OyQdEKOITANXBLCWoykny9hCqpQw',
    appId: '1:73746867862:web:f7a8ad8496875e9b2c84b7',
    messagingSenderId: '73746867862',
    projectId: 'group-scorecard',
    authDomain: 'group-scorecard.firebaseapp.com',
    storageBucket: 'group-scorecard.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnJvCDGfLyudSQdQXPUT_0b7c9jWsRRc0',
    appId: '1:73746867862:android:a42d214bc8f15d142c84b7',
    messagingSenderId: '73746867862',
    projectId: 'group-scorecard',
    storageBucket: 'group-scorecard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC24f5MX9kIg6YD8c4sUKlKTNDrEc1FUsY',
    appId: '1:73746867862:ios:0909a533514805132c84b7',
    messagingSenderId: '73746867862',
    projectId: 'group-scorecard',
    storageBucket: 'group-scorecard.appspot.com',
    iosBundleId: 'com.example.groupScorecard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC24f5MX9kIg6YD8c4sUKlKTNDrEc1FUsY',
    appId: '1:73746867862:ios:0909a533514805132c84b7',
    messagingSenderId: '73746867862',
    projectId: 'group-scorecard',
    storageBucket: 'group-scorecard.appspot.com',
    iosBundleId: 'com.example.groupScorecard',
  );
}
